#!/usr/bin/env bash
# author: deadc0de6 (https://github.com/deadc0de6)
# Copyright (c) 2024, deadc0de6

IN_CICD=${GITHUB_WORKFLOW:-}
to_be_cleared=()

# add a file/directory to be cleared
# on exit
#
# $1: file path to clear
clear_on_exit()
{
  local len="${#to_be_cleared[*]}"
  to_be_cleared["${len}"]="$1"
  if [ "${len}" = "0" ]; then
    # set trap
    trap on_exit EXIT
  fi
}

# clear files
on_exit()
{
  for i in "${to_be_cleared[@]}"; do
    rm -rf "${i}"
  done
}

cat_file()
{
  [ -n "${IN_CICD}" ] && return
  echo "---------- $(basename "${1}") ----------"
  cat "${1}"
  echo "--------------------"
}

# osx tricks
# brew install coreutils gnu-sed
if [[ $OSTYPE == 'darwin'* ]]; then
  mktemp() {
    gmktemp "$@"
  }
  stat() {
    gstat "$@"
  }
  sed() {
    gsed "$@"
  }
  wc() {
    gwc "$@"
  }
  date() {
    gdate "$@"
  }
  chmod() {
    gchmod "$@"
  }
  readlink() {
    greadlink "$@"
  }
  realpath() {
    grealpath "$@"
  }
  du() {
    gdu "$@"
  }

  export -f mktemp
  export -f stat
  export -f sed
  export -f wc
  export -f date
  export -f chmod
  export -f readlink
  export -f realpath
fi